import spacy

nlp = spacy.load("en_core_web_trf")

text = (
        'frivolities of childhood, he had acquired the stability of a man, and\n '
        'the most casual observer could scarcely fail to be attracted by his\n '
        'bright, yet thoughtful countenance. At an early period of his life he\n '
        'had realized all the difficulties of his position, and had made a\n '
        'resolution, from which nothing tempted him to flinch, that he would\n '
        'carve out for himself an honourable and independent career. Lithe and\n '
        'agile in his movements, he was an adept in every kind of athletic\n '
        'exercise; and so marvellous was his success in everything he undertook,\n '
        'that he might almost be supposed to be one of those gifted mortals who\n '
        'have two right hands and two left feet.\n '
        '\n '
        'Until he was four years old the little orphan had found a home in one\n '
        'of those institutions in America where forsaken children are sure of an\n '
        'asylum, and he was subsequently sent to an industrial school supported\n '
        'by charitable aid, where he learnt reading, writing, and arithmetic.\n '
        'From the days of infancy he had never deviated from the expression of\n '
        'his wish to be a sailor, and accordingly, as soon as he was eight, he\n '
        'was placed as cabin-boy on board one of the ships that navigate the\n '
        'Southern Seas. The officers all took a peculiar interest in him, and he\n '
        'received, in consequence, a thoroughly good grounding in the duties and\n '
        'discipline of a seaman\'s life. There was no room to doubt that he must\n '
        'ultimately rise to eminence in his profession, for when a child from\n '
        'the very first has been trained in the knowledge that he must gain his\n '
        'bread by the sweat of his brow, it is comparatively rare that he lacks\n '
        'the will to do so.\n '
        '\n '
        'Whilst he was still acting as cabin-boy on one of those\n '
        'trading-vessels, Dick attracted the notice of Captain Hull, who took a\n '
        'fancy to the lad and introduced him to his employer. Mr. Weldon at once\n '
        'took a lively interest in Dick\'s welfare, and had his education\n '
        'continued in San Francisco, taking care that he was instructed in the\n '
        'doctrines of the Roman Catholic Church, to which his own family\n '
        'belonged.\n '
        '\n '
        'Throughout his studies Dick Sands\' favourite subjects were always those\n '
        'which had a reference to his future profession; he mastered the details\n '
        'of the geography of the world; he applied himself diligently to such\n '
        'branches of mathematics as were necessary for the science of\n '
        'navigation; whilst for recreation in his hours of leisure, he would\n '
        'greedily devour every book of adventure in travel that came in his way.\n '
        'Nor did he omit duly to combine the practical with the theoretical; and\n '
        'when he was bound apprentice on board the "Pilgrim," a vessel not only\n '
        'belonging to his benefactor, but under the command of his kind friend\n '
        'Captain Hull, he congratulated himself most heartily, and felt that the\n '
        'experience he should gain in the southern whale-fisheries could hardly\n '
        'fail to be of service to him in after-life. A first-rate sailor ought\n '
        'to be a first-rate fisherman too.\n '
        '\n '
        'It was a matter of the greatest pleasure to Dick Sands when he heard to\n '
        'his surprise that Mrs. Weldon was about to become a passenger on board\n '
        'the "Pilgrim." His devotion to the family of his benefactor was large\n '
        'and genuine. For several years Mrs. Weldon had acted towards him little\n '
        'short of a mother\'s part, and for Jack, although he never forgot the\n '
        'difference in their position, he entertained well-nigh a brother\'s\n '
        'affection. His friends had the satisfaction of being assured that they\n '
        'had sown the seeds of kindness on a generous soil, for there was no\n '
        'room to doubt that the heart of the orphan boy was overflowing with\n '
        'sincere gratitude. Should the occasion arise, ought he not, he asked,\n '
        'to be ready to sacrifice everything in behalf of those to whom he was\n '
        'indebted not only for his start in life, but for the knowledge of all\n '
        'that was right and holy?\n '
        '\n '
        'Confiding in the good principles of her protégé, Mrs. Weldon had no\n '
        'hesitation in entrusting her little son to his especial charge. During\n '
        'the frequent periods of leisure, when the sea was fair, and the sails\n '
        'required no shifting, the apprentice was never weary of amusing Jack by\n '
        'making him familiar with the practice of a sailor\'s craft; he made him\n '
        'scramble up the shrouds, perch upon the yards, and slip down the\n '
        'back-stays; and the mother had no alarm; her assurance of Dick Sands\'n '
        'ability and watchfulness to protect her boy was so complete that she\n '
        'could only rejoice in an occupation for him that seemed more than\n '
        'anything to restore the colour he had lost in his recent illness.\n '
        '\n '
        'Time passed on without incident; and had it not been for the constant\n '
        'prevalence of an adverse wind, neither passengers nor crew could have\n '
        'found the least cause of complaint. The pertinacity, however, with\n '
        'which the wind kept to the east could not do otherwise than make\n '
        'Captain Hull somewhat concerned; it absolutely prevented him from\n '
        'getting his ship into her proper course, and he could not altogether\n '
        'suppress his misgiving that the calms near the Tropic of Capricorn, and\n '
        'the equatorial current driving him on westwards, would entail a delay\n '
        'that might be serious.\n '
        '\n '
        '[Illustration: Dick and little Jack.]\n '
        '\n '
        'It was principally on Mrs. Weldon\'s account that the Captain began to\n '
        'feel uneasiness, and he made up his mind that if he could hail a vessel\n '
        'proceeding to America he should advise his passengers to embark on her;\n '
        'unfortunately, however, he felt that they were still in a latitude far\n '
        'too much to the south to make it likely that they should sight a\n '
        'steamer going to Panama; and at that date, communication between\n '
        'Australia and the New World was much less frequent than it has since\n '
        'become.\n '
        '\n '
        'Still, nothing occurred to interrupt the general monotony of the voyage\n '
        'until the 2nd of February, the date at which our narrative commences.\n '
        '\n '
        'It was about nine o\'clock in the morning of that day that Dick and\n '
        'little Jack had perched themselves together on the top-mast-yards. The\n '
        'weather was very clear, and they could see the horizon right round\n '
        'except the section behind them, hidden by the brigantine-sail on the\n '
        'main-mast. Below them, the bowsprit seemed to lie along the water with\n '
        'its stay-sails attached like three unequal wings; from the lads\' feet\n '
        'to the deck was the smooth surface of the fore-mast; and above their\n '
        'heads nothing but the small top-sail and the top-mast. The schooner was\n '
        'running on the larboard tack as close to the wind as possible.\n '
        '\n '
        'Dick Sand was pointing out to Jack how well the ship was ballasted, and\n '
        'was trying to explain how it was impossible for her to capsize, however\n '
        'much she heeled to starboard, when suddenly the little fellow cried\n '
        'out,--\n '
        '\n '
        '"I can see something in the water!"\n '
        '\n '
        '"Where? what?" exclaimed Dick, clambering to his feet upon the yard.\n '
        '\n '
        '"There!" said the child, directing attention to the portion of the\n '
        'sea-surface that was visible between the stay-sails.\n '
        '\n '
        'Dick fixed his gaze intently for a moment, and then shouted out\n '
        'lustily,--\n '
        '\n '
        '"Look out in front, to starboard! There is something afloat. To\n '
        'windward, look out!"\n '
        '\n '
        '\n '
        '\n '
        '\n '
        'CHAPTER III.\n '
        '\n '
        'A RESCUE.\n '
        '\n '
        '\n '
        'At the sound of Dick\'s voice all the crew, in a moment, were upon the\n '
        'alert. The men who were not on watch rushed to the deck, and Captain\n '
        'Hull hurried from his cabin to the bows. Mrs. Weldon, Nan, and even\n '
        'Cousin Benedict leaned over the starboard taffrails, eager to get a\n '
        'glimpse of what had thus suddenly attracted the attention of the young\n '
        'apprentice. With his usual indifference, Negoro did not leave his\n '
        'cabin, and was the only person on board who did not share the general\n '
        'excitement.\n '
        '\n '
        'Speculations were soon rife as to what could be the nature of the\n '
        'floating object which could be discerned about three miles ahead.\n '
        'Suggestions of various character were freely made. One of the sailors\n '
        'declared that it looked to him only like an abandoned raft, but Mrs.\n '
        'Weldon observed quickly that if it were a raft it might be carrying\n '
        'some unfortunate shipwrecked men who must be rescued if possible.\n '
        'Cousin Benedict asserted that it was nothing more nor less than a huge\n '
        'sea-monster; but the captain soon arrived at the conviction that it was\n '
        'the hull of a vessel that had heeled over on to its side, an opinion\n '
        'with which Dick thoroughly coincided, and went so far as to say that he\n '
        'believed he could make out the copper keel glittering in the sun.\n '
        '\n '
        '"Luff, Bolton, luff!" shouted Captain Hull to the helmsman; "we will at\n '
        'any rate lose no time in getting alongside."\n '
        '\n '
        '"Ay, ay, sir," answered the helmsman, and the "Pilgrim" in an instant\n '
        'was steered according to orders.\n '
        '\n '
        'In spite, however, of the convictions of the captain and Dick, Cousin\n '
        'Benedict would not be moved from his opinion that the object of their\n '
        'curiosity was some huge cetacean.\n '
        '\n '
        '"It is certainly dead, then," remarked Mrs. Weldon; "it is perfectly\n '
        'motionless."\n '
        '\n '
        '"Oh, that\'s because it is asleep," said Benedict, who, although he\n '
        'would have willingly given up all the whales in the ocean for one rare\n '
        'specimen of an insect, yet could not surrender his own belief.\n '
        '\n '
        '"Easy, Bolton, easy!" shouted the captain when they were getting nearer\n '
        'the floating mass; "don\'t let us be running foul of the thing; no good\n '
        'could come from knocking a hole in our side; keep out from it a good\n '
        'cable\'s length."\n '
        '\n '
        '"Ay, ay, sir," replied the helmsman, in his usual cheery way; and by an\n '
        'easy turn of the helm the "Pilgrim\'s" course was slightly modified so\n '
        'as to avoid all fear of collision.\n '
        '\n '
        'The excitement of the sailors by this time had become more intense.\n '
        'Ever since the distance had been less than a mile all doubt had\n '
        'vanished, and it was certain that what was attracting their attention\n '
        'was the hull of a capsized ship. They knew well enough the established\n '
        'rule that a third of all salvage is the right of the finders, and they\n '
        'were filled with the hope that the hull they were nearing might contain\n '
        'an undamaged cargo, and be "a good haul," to compensate them for their\n '
        'ill-success in the last season.\n '
        '\n '
        'A quarter of an hour later and the "Pilgrim" was within half a mile of\n '
        'the deserted vessel, facing her starboard side. Water-logged to her\n '
        'bulwarks, she had heeled over so completely that it would have been\n '
        'next to impossible to stand upon her deck. Of her masts nothing was to\n '
        'be seen; a few ends of cordage were all that remained of her shrouds,\n '
        'and the try-sail chains were hanging all broken. On the starboard flank\n '
        'was an enormous hole.\n '
        '\n '
        '"Something or other has run foul of her," said Dick.\n '
        '\n '
        '"No doubt of that," replied the captain; "the only wonder is that she\n '
        'did not sink immediately."\n '
        '\n '
        '"Oh, how I hope the poor crew have been saved!" exclaimed Mrs Weldon.\n '
        '\n '
        '"Most probably," replied the captain, "they would all have taken to the\n '
        'boats. It is as likely as not that the ship which did the mischief\n '
        'would continue its course quite unconcerned."\n '
        '\n '
        '"Surely, you cannot mean," cried Mrs Weldon, "that any one could be\n '
        'capable of such inhumanity?"\n '
        '\n '
        '"Only too probable," answered Captain Hull, "unfortunately, such\n '
        'instances are very far from rare."\n '
        '\n '
        'He scanned the drifting ship carefully and continued,--\n '
        '\n '
        '"No, I cannot see any sign of boats here, I should guess that the crew\n '
        'have made an attempt to get to land, at such a distance as this,\n '
        'however, from America or from the islands of the Pacific I should be\n '
        'afraid that it must be hopeless."\n '
        '\n '
        '"Is it not possible," asked Mrs Weldon, "that some poor creature may\n '
        'still survive on board, who can tell what has happened?"\n '
        '\n '
        '"Hardly likely, madam; otherwise there would have been some sort of a\n '
        'signal in sight. But it is a matter about which we will make sure."\n '
        '\n '
        'The captain waved his hand a little in the direction in which he wished\n '
        'to go, and said quietly,--\n '
        '\n '
        '"Luff, Bolton, luff a bit!"\n '
        '\n '
        'The "Pilgrim" by this time was not much more than three cables\' lengths\n '
        'from the ship, there was still no token of her being otherwise than\n '
        'utterly deserted, when Dick Sands suddenly exclaimed,--\n '
        '\n '
        '"Hark! if I am not much mistaken, that is a dog barking!"\n '
        '\n '
        'Every one listened attentively; it was no fancy on Dick\'s part, sure\n '
        'enough a stifled barking could be heard, as if some unfortunate dog had\n '
        'been imprisoned beneath the hatchways; but as the deck was not yet\n '
        'visible, it was impossible at present to determine the precise truth.\n '
        '\n '
        'Mrs Weldon pleaded,--\n '
        '\n '
        '"If it is only a dog, captain, let it be saved."\n '
        '\n '
        '"Oh, yes, yes, mamma, the dog must be saved!" cried little Jack; "I\n '
        'will go and get a bit of sugar ready for it."\n '
        '\n '
        '[Illustration: Negoro had approached without being noticed by any one]\n '
        '\n '
        '"A bit of sugar, my child, will not be much for a starved dog."\n '
        '\n '
        '"Then it shall have my soup, and I will do without," said the boy, and\n '
        'he kept shouting, "Good dog! good dog!" until he persuaded himself that\n '
        'he heard the animal responding to his call.\n '
        '\n '
        'The vessels were now scarcely three hundred feet apart; the barking was\n '
        'more and more distinct, and presently a great dog was seen clinging to\n '
        'the starboard netting. It barked more desperately than ever.\n '
        '\n '
        '"Howick," said Captain Hull, calling to the boatswain, "heave to, and\n '
        'lower the small boat."\n '
        '\n '
        'The sails were soon trimmed so as to bring the schooner to a standstill\n '
        'within half a cable\'s length of the disabled craft, the boat was\n '
        'lowered, and the captain and Dick, with a couple of sailors, went on\n '
        'board. The dog kept up a continual yelping; it made the most vigourous\n '
        'efforts to retain its hold upon the netting, but perpetually slipped\n '
        'backwards and fell off again upon the inclining deck. It was soon\n '
        'manifest, however, that all the noise the creature was making was not\n '
        'directed exclusively towards those who were coming to its rescue, and\n '
        'Mrs. Weldon could not divest herself of the impression that there must\n '
        'be some survivors still on board. All at once the animal changed its\n '
        'gestures. Instead of the crouching attitude and supplicating whine with\n '
        'which it seemed to be imploring the compassion of those who were\n '
        'nearing it, it suddenly appeared to become bursting with violence and\n '
        'furious with rage.\n '
        '\n '
        '"What ails the brute?" exclaimed Captain Hull.\n '
        '\n '
        'But already the boat was on the farther side of the wrecked ship, and\n '
        'the captain was not in a position to see that Negoro the cook had just\n '
        'come on to the schooner\'s deck, or that it was obvious that it was\n '
        'against him that the dog had broken out in such obstreperous fury.\n '
        'Negoro had approached without being noticed by any one; he made his way\n '
        '\n '

)

# Split the text by new lines
lines = text.split('\n')

type = []
# Process each line
for i, line in enumerate(lines):
    doc = nlp(line)
    entities = []
    for ent in doc.ents:
        if (ent.start-1 == ent.end-2):
            entities.append([ent.start-1, ent.text, ent.label_])
        else:
            entities.append([ent.start-1, ent.end-2, ent.text, ent.label_])
    for ent in entities:
        if ent != []:
            if len(ent) == 3:
                print(f'({i}, {ent[0]}) - {ent[2]} = Line {i}: {ent}')
                type.append(ent[2])
                with open("result.txt", "a+") as f:
                    f.write(f'({i}, {ent[0]}) - {ent[2]} = Line {i}: {ent}\n')
            elif len(ent) == 4:
                print(f'(({i}, {ent[0]}), {i}, {ent[1]})) - {ent[3]} = Line {i}: {ent}')
                type.append(ent[3])
                with open("result.txt", "a+") as f:
                        f.write(f'(({i}, {ent[0]}), ({i}, {ent[1]})) - {ent[3]} = Line {i}: {ent}\n')
            else:
                print(ent)
print(set(type))