import spacy

# Load English tokenizer, tagger, parser and NER
nlp = spacy.load("en_core_web_trf")

# Process whole documents
text = ('frivolities of childhood, he had acquired the stability of a man, and ' 
        'the most casual observer could scarcely fail to be attracted by his ' 
        'bright, yet thoughtful countenance. At an early period of his life he ' 
        'had realized all the difficulties of his position, and had made a ' 
        'resolution, from which nothing tempted him to flinch, that he would ' 
        'carve out for himself an honourable and independent career. Lithe and ' 
        'agile in his movements, he was an adept in every kind of athletic ' 
        'exercise; and so marvellous was his success in everything he undertook, ' 
        'that he might almost be supposed to be one of those gifted mortals who ' 
        'have two right hands and two left feet. ' 
        ' ' 
        'Until he was four years old the little orphan had found a home in one ' 
        'of those institutions in America where forsaken children are sure of an ' 
        'asylum, and he was subsequently sent to an industrial school supported ' 
        'by charitable aid, where he learnt reading, writing, and arithmetic. ' 
        'From the days of infancy he had never deviated from the expression of ' 
        'his wish to be a sailor, and accordingly, as soon as he was eight, he ' 
        'was placed as cabin-boy on board one of the ships that navigate the ' 
        'Southern Seas. The officers all took a peculiar interest in him, and he ' 
        'received, in consequence, a thoroughly good grounding in the duties and ' 
        'discipline of a seaman\'s life. There was no room to doubt that he must ' 
        'ultimately rise to eminence in his profession, for when a child from ' 
        'the very first has been trained in the knowledge that he must gain his ' 
        'bread by the sweat of his brow, it is comparatively rare that he lacks ' 
        'the will to do so. ' 
        ' ' 
        'Whilst he was still acting as cabin-boy on one of those ' 
        'trading-vessels, Dick attracted the notice of Captain Hull, who took a ' 
        'fancy to the lad and introduced him to his employer. Mr. Weldon at once ' 
        'took a lively interest in Dick\'s welfare, and had his education ' 
        'continued in San Francisco, taking care that he was instructed in the ' 
        'doctrines of the Roman Catholic Church, to which his own family ' 
        'belonged. ' 
        ' ' 
        'Throughout his studies Dick Sands\' favourite subjects were always those ' 
        'which had a reference to his future profession; he mastered the details ' 
        'of the geography of the world; he applied himself diligently to such ' 
        'branches of mathematics as were necessary for the science of ' 
        'navigation; whilst for recreation in his hours of leisure, he would ' 
        'greedily devour every book of adventure in travel that came in his way. ' 
        'Nor did he omit duly to combine the practical with the theoretical; and ' 
        'when he was bound apprentice on board the "Pilgrim," a vessel not only ' 
        'belonging to his benefactor, but under the command of his kind friend ' 
        'Captain Hull, he congratulated himself most heartily, and felt that the ' 
        'experience he should gain in the southern whale-fisheries could hardly ' 
        'fail to be of service to him in after-life. A first-rate sailor ought ' 
        'to be a first-rate fisherman too. ' 
        ' ' 
        'It was a matter of the greatest pleasure to Dick Sands when he heard to ' 
        'his surprise that Mrs. Weldon was about to become a passenger on board ' 
        'the "Pilgrim." His devotion to the family of his benefactor was large ' 
        'and genuine. For several years Mrs. Weldon had acted towards him little ' 
        'short of a mother\'s part, and for Jack, although he never forgot the ' 
        'difference in their position, he entertained well-nigh a brother\'s ' 
        'affection. His friends had the satisfaction of being assured that they ' 
        'had sown the seeds of kindness on a generous soil, for there was no ' 
        'room to doubt that the heart of the orphan boy was overflowing with ' 
        'sincere gratitude. Should the occasion arise, ought he not, he asked, ' 
        'to be ready to sacrifice everything in behalf of those to whom he was ' 
        'indebted not only for his start in life, but for the knowledge of all ' 
        'that was right and holy? ' 
        ' ' 
        'Confiding in the good principles of her protégé, Mrs. Weldon had no ' 
        'hesitation in entrusting her little son to his especial charge. During ' 
        'the frequent periods of leisure, when the sea was fair, and the sails ' 
        'required no shifting, the apprentice was never weary of amusing Jack by ' 
        'making him familiar with the practice of a sailor\'s craft; he made him ' 
        'scramble up the shrouds, perch upon the yards, and slip down the ' 
        'back-stays; and the mother had no alarm; her assurance of Dick Sands\' ' 
        'ability and watchfulness to protect her boy was so complete that she ' 
        'could only rejoice in an occupation for him that seemed more than ' 
        'anything to restore the colour he had lost in his recent illness. ' 
        ' ' 
        'Time passed on without incident; and had it not been for the constant ' 
        'prevalence of an adverse wind, neither passengers nor crew could have ' 
        'found the least cause of complaint. The pertinacity, however, with ' 
        'which the wind kept to the east could not do otherwise than make ' 
        'Captain Hull somewhat concerned; it absolutely prevented him from ' 
        'getting his ship into her proper course, and he could not altogether ' 
        'suppress his misgiving that the calms near the Tropic of Capricorn, and ' 
        'the equatorial current driving him on westwards, would entail a delay ' 
        'that might be serious. ' 
        ' ' 
        '[Illustration: Dick and little Jack.] ' 
        ' ' 
        'It was principally on Mrs. Weldon\'s account that the Captain began to ' 
        'feel uneasiness, and he made up his mind that if he could hail a vessel ' 
        'proceeding to America he should advise his passengers to embark on her; ' 
        'unfortunately, however, he felt that they were still in a latitude far ' 
        'too much to the south to make it likely that they should sight a ' 
        'steamer going to Panama; and at that date, communication between ' 
        'Australia and the New World was much less frequent than it has since ' 
        'become. ' 
        ' ' 
        'Still, nothing occurred to interrupt the general monotony of the voyage ' 
        'until the 2nd of February, the date at which our narrative commences. ' 
        ' ' 
        'It was about nine o\'clock in the morning of that day that Dick and ' 
        'little Jack had perched themselves together on the top-mast-yards. The ' 
        'weather was very clear, and they could see the horizon right round ' 
        'except the section behind them, hidden by the brigantine-sail on the ' 
        'main-mast. Below them, the bowsprit seemed to lie along the water with ' 
        'its stay-sails attached like three unequal wings; from the lads\' feet ' 
        'to the deck was the smooth surface of the fore-mast; and above their ' 
        'heads nothing but the small top-sail and the top-mast. The schooner was ' 
        'running on the larboard tack as close to the wind as possible. ' 
        ' ' 
        'Dick Sand was pointing out to Jack how well the ship was ballasted, and ' 
        'was trying to explain how it was impossible for her to capsize, however ' 
        'much she heeled to starboard, when suddenly the little fellow cried ' 
        'out,-- ' 
        ' ' 
        '"I can see something in the water!" ' 
        ' ' 
        '"Where? what?" exclaimed Dick, clambering to his feet upon the yard. ' 
        ' ' 
        '"There!" said the child, directing attention to the portion of the ' 
        'sea-surface that was visible between the stay-sails. ' 
        ' ' 
        'Dick fixed his gaze intently for a moment, and then shouted out ' 
        'lustily,-- ' 
        ' ' 
        '"Look out in front, to starboard! There is something afloat. To ' 
        'windward, look out!" ' 
        ' ' 
        ' ' 
        ' ' 
        ' ' 
        'CHAPTER III. ' 
        ' ' 
        'A RESCUE. ' 
        ' ' 
        ' ' 
        'At the sound of Dick\'s voice all the crew, in a moment, were upon the ' 
        'alert. The men who were not on watch rushed to the deck, and Captain ' 
        'Hull hurried from his cabin to the bows. Mrs. Weldon, Nan, and even ' 
        'Cousin Benedict leaned over the starboard taffrails, eager to get a ' 
        'glimpse of what had thus suddenly attracted the attention of the young ' 
        'apprentice. With his usual indifference, Negoro did not leave his ' 
        'cabin, and was the only person on board who did not share the general ' 
        'excitement. ' 
        ' ' 
        'Speculations were soon rife as to what could be the nature of the ' 
        'floating object which could be discerned about three miles ahead. ' 
        'Suggestions of various character were freely made. One of the sailors ' 
        'declared that it looked to him only like an abandoned raft, but Mrs. ' 
        'Weldon observed quickly that if it were a raft it might be carrying ' 
        'some unfortunate shipwrecked men who must be rescued if possible. ' 
        'Cousin Benedict asserted that it was nothing more nor less than a huge ' 
        'sea-monster; but the captain soon arrived at the conviction that it was ' 
        'the hull of a vessel that had heeled over on to its side, an opinion ' 
        'with which Dick thoroughly coincided, and went so far as to say that he ' 
        'believed he could make out the copper keel glittering in the sun. ' 
        ' ' 
        '"Luff, Bolton, luff!" shouted Captain Hull to the helmsman; "we will at ' 
        'any rate lose no time in getting alongside." ' 
        ' ' 
        '"Ay, ay, sir," answered the helmsman, and the "Pilgrim" in an instant ' 
        'was steered according to orders. ' 
        ' ' 
        'In spite, however, of the convictions of the captain and Dick, Cousin ' 
        'Benedict would not be moved from his opinion that the object of their ' 
        'curiosity was some huge cetacean. ' 
        ' ' 
        '"It is certainly dead, then," remarked Mrs. Weldon; "it is perfectly ' 
        'motionless." ' 
        ' ' 
        '"Oh, that\'s because it is asleep," said Benedict, who, although he ' 
        'would have willingly given up all the whales in the ocean for one rare ' 
        'specimen of an insect, yet could not surrender his own belief. ' 
        ' ' 
        '"Easy, Bolton, easy!" shouted the captain when they were getting nearer ' 
        'the floating mass; "don\'t let us be running foul of the thing; no good ' 
        'could come from knocking a hole in our side; keep out from it a good ' 
        'cable\'s length." ' 
        ' ' 
        '"Ay, ay, sir," replied the helmsman, in his usual cheery way; and by an ' 
        'easy turn of the helm the "Pilgrim\'s" course was slightly modified so ' 
        'as to avoid all fear of collision. ' 
        ' ' 
        'The excitement of the sailors by this time had become more intense. ' 
        'Ever since the distance had been less than a mile all doubt had ' 
        'vanished, and it was certain that what was attracting their attention ' 
        'was the hull of a capsized ship. They knew well enough the established ' 
        'rule that a third of all salvage is the right of the finders, and they ' 
        'were filled with the hope that the hull they were nearing might contain ' 
        'an undamaged cargo, and be "a good haul," to compensate them for their ' 
        'ill-success in the last season. ' 
        ' ' 
        'A quarter of an hour later and the "Pilgrim" was within half a mile of ' 
        'the deserted vessel, facing her starboard side. Water-logged to her ' 
        'bulwarks, she had heeled over so completely that it would have been ' 
        'next to impossible to stand upon her deck. Of her masts nothing was to ' 
        'be seen; a few ends of cordage were all that remained of her shrouds, ' 
        'and the try-sail chains were hanging all broken. On the starboard flank ' 
        'was an enormous hole. ' 
        ' ' 
        '"Something or other has run foul of her," said Dick. ' 
        ' ' 
        '"No doubt of that," replied the captain; "the only wonder is that she ' 
        'did not sink immediately." ' 
        ' ' 
        '"Oh, how I hope the poor crew have been saved!" exclaimed Mrs Weldon. ' 
        ' ' 
        '"Most probably," replied the captain, "they would all have taken to the ' 
        'boats. It is as likely as not that the ship which did the mischief ' 
        'would continue its course quite unconcerned." ' 
        ' ' 
        '"Surely, you cannot mean," cried Mrs Weldon, "that any one could be ' 
        'capable of such inhumanity?" ' 
        ' ' 
        '"Only too probable," answered Captain Hull, "unfortunately, such ' 
        'instances are very far from rare." ' 
        ' ' 
        'He scanned the drifting ship carefully and continued,-- ' 
        ' ' 
        '"No, I cannot see any sign of boats here, I should guess that the crew ' 
        'have made an attempt to get to land, at such a distance as this, ' 
        'however, from America or from the islands of the Pacific I should be ' 
        'afraid that it must be hopeless." ' 
        ' ' 
        '"Is it not possible," asked Mrs Weldon, "that some poor creature may ' 
        'still survive on board, who can tell what has happened?" ' 
        ' ' 
        '"Hardly likely, madam; otherwise there would have been some sort of a ' 
        'signal in sight. But it is a matter about which we will make sure." ' 
        ' ' 
        'The captain waved his hand a little in the direction in which he wished ' 
        'to go, and said quietly,-- ' 
        ' ' 
        '"Luff, Bolton, luff a bit!" ' 
        ' ' 
        'The "Pilgrim" by this time was not much more than three cables\' lengths ' 
        'from the ship, there was still no token of her being otherwise than ' 
        'utterly deserted, when Dick Sands suddenly exclaimed,-- ' 
        ' ' 
        '"Hark! if I am not much mistaken, that is a dog barking!" ' 
        ' ' 
        'Every one listened attentively; it was no fancy on Dick\'s part, sure ' 
        'enough a stifled barking could be heard, as if some unfortunate dog had ' 
        'been imprisoned beneath the hatchways; but as the deck was not yet ' 
        'visible, it was impossible at present to determine the precise truth. ' 
        ' ' 
        'Mrs Weldon pleaded,-- ' 
        ' ' 
        '"If it is only a dog, captain, let it be saved." ' 
        ' ' 
        '"Oh, yes, yes, mamma, the dog must be saved!" cried little Jack; "I ' 
        'will go and get a bit of sugar ready for it." ' 
        ' ' 
        '[Illustration: Negoro had approached without being noticed by any one] ' 
        ' ' 
        '"A bit of sugar, my child, will not be much for a starved dog." ' 
        ' ' 
        '"Then it shall have my soup, and I will do without," said the boy, and ' 
        'he kept shouting, "Good dog! good dog!" until he persuaded himself that ' 
        'he heard the animal responding to his call. ' 
        ' ' 
        'The vessels were now scarcely three hundred feet apart; the barking was ' 
        'more and more distinct, and presently a great dog was seen clinging to ' 
        'the starboard netting. It barked more desperately than ever. ' 
        ' ' 
        '"Howick," said Captain Hull, calling to the boatswain, "heave to, and ' 
        'lower the small boat." ' 
        ' ' 
        'The sails were soon trimmed so as to bring the schooner to a standstill ' 
        'within half a cable\'s length of the disabled craft, the boat was ' 
        'lowered, and the captain and Dick, with a couple of sailors, went on ' 
        'board. The dog kept up a continual yelping; it made the most vigourous ' 
        'efforts to retain its hold upon the netting, but perpetually slipped ' 
        'backwards and fell off again upon the inclining deck. It was soon ' 
        'manifest, however, that all the noise the creature was making was not ' 
        'directed exclusively towards those who were coming to its rescue, and ' 
        'Mrs. Weldon could not divest herself of the impression that there must ' 
        'be some survivors still on board. All at once the animal changed its ' 
        'gestures. Instead of the crouching attitude and supplicating whine with ' 
        'which it seemed to be imploring the compassion of those who were ' 
        'nearing it, it suddenly appeared to become bursting with violence and ' 
        'furious with rage. ' 
        ' ' 
        '"What ails the brute?" exclaimed Captain Hull. ' 
        ' ' 
        'But already the boat was on the farther side of the wrecked ship, and ' 
        'the captain was not in a position to see that Negoro the cook had just ' 
        'come on to the schooner\'s deck, or that it was obvious that it was ' 
        'against him that the dog had broken out in such obstreperous fury. ' 
        'Negoro had approached without being noticed by any one; he made his way ' 
        ' ' 

        )
doc = nlp(text)

# Analyze syntax
print("Noun phrases:", [chunk.text for chunk in doc.noun_chunks])
print("Verbs:", [token.lemma_ for token in doc if token.pos_ == "VERB"])

# Find named entities, phrases and concepts
for entity in doc.ents:
    print(entity.text, entity.label_)
